version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: bounduser
      POSTGRES_PASSWORD: boundpass
      POSTGRES_DB: bounddb
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: npm run start:dev
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://bounduser:boundpass@db:5432/bounddb

  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"

volumes:
  db_data:
