version: '3.8'

services:
  frontend:
    build:
      context: ../client
      dockerfile: frontend.Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ../client:/app
    command: yarn start

  backend:
    build:
      context: ../server
      dockerfile: backend.Dockerfile
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=development
      - PORT=5000
    volumes:
      - ../server:/app
    command: npm run dev

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: bound_user
      POSTGRES_PASSWORD: bound_password
      POSTGRES_DB: bound_db
    ports:
      - '5432:5432'
