const express = require('express');
const app = express();
app.use(express.json());

// Add your routes here

module.exports = app;
const userRoutes = require('./routes/user');
app.use('/api/user', userRoutes);
const userRoutes = require('./routes/user');
app.use('/api/user', userRoutes);
const userRoutes = require('./routes/user');
app.use('/api/user', userRoutes);
const userRoutes = require('./routes/user');
app.use('/api/user', userRoutes);
const userRoutes = require('./routes/user');
app.use('/api/user', userRoutes);
const userRoutes = require('./routes/user');
app.use('/api/user', userRoutes);
const postRoutes = require('./routes/posts');
app.use('/api/posts', postRoutes);
const postRoutes = require('./routes/posts');
app.use('/api/posts', postRoutes);
const reactionsRoutes = require('./routes/reactions');
app.use('/api/posts', reactionsRoutes);
const commentsRoutes = require('./routes/comments');
app.use('/api/posts', commentsRoutes);
const reactionsRoutes = require('./routes/reactions');
app.use('/api/posts', reactionsRoutes);
const commentsRoutes = require('./routes/comments');
app.use('/api/posts', commentsRoutes);
const reactionsRoutes = require('./routes/reactions');
app.use('/api/posts', reactionsRoutes);
const commentsRoutes = require('./routes/comments');
app.use('/api/posts', commentsRoutes);
const reactionsRoutes = require('./routes/reactions');
app.use('/api/posts', reactionsRoutes);
const commentsRoutes = require('./routes/comments');
app.use('/api/posts', commentsRoutes);
const reactionsRoutes = require('./routes/reactions');
app.use('/api/posts', reactionsRoutes);
const commentsRoutes = require('./routes/comments');
app.use('/api/posts', commentsRoutes);
const reactionsRoutes = require('./routes/reactions');
app.use('/api/posts', reactionsRoutes);
const commentsRoutes = require('./routes/comments');
app.use('/api/posts', commentsRoutes);
const reactionsRoutes = require('./routes/reactions');
app.use('/api/posts', reactionsRoutes);
const commentsRoutes = require('./routes/comments');
app.use('/api/posts', commentsRoutes);
const reactionsRoutes = require('./routes/reactions');
app.use('/api/posts', reactionsRoutes);
const commentsRoutes = require('./routes/comments');
app.use('/api/posts', commentsRoutes);
const groupRoutes = require('./routes/groups');
app.use('/api/groups', groupRoutes);
const groupRoutes = require('./routes/groups');
app.use('/api/groups', groupRoutes);
const groupRoutes = require('./routes/groups');
app.use('/api/groups', groupRoutes);
const groupRoutes = require('./routes/groups');
app.use('/api/groups', groupRoutes);
const notificationRoutes = require('./routes/notifications');
app.use('/api/notifications', notificationRoutes);
const notificationRoutes = require('./routes/notifications');
app.use('/api/notifications', notificationRoutes);
const profileRoutes = require('./routes/profile');
app.use('/api/profile', profileRoutes);
const feedsRoutes = require('./routes/feeds');
app.use('/api/feeds', feedsRoutes);
const eventsRoutes = require('./routes/events');
app.use('/api/events', eventsRoutes);
const eventsRoutes = require('./routes/events');
app.use('/api/events', eventsRoutes);
const moderationRoutes = require('./routes/moderation');
app.use('/api/moderation', moderationRoutes);
const moderationRoutes = require("./routes/moderation");
app.use("/api/moderation", moderationRoutes);
const privacyRoutes = require("./routes/privacy");
app.use("/api/privacy", privacyRoutes);
const groupRoutes = require("./routes/groups");
app.use("/api/groups", groupRoutes);
const privacyRoutes = require("./routes/privacy");
app.use("/api/privacy", privacyRoutes);
const messagesRoutes = require("./routes/messages");
app.use("/api/messages", messagesRoutes);
const privacyRoutes = require("./routes/privacy");
app.use("/api/privacy", privacyRoutes);
const feedbackRoutes = require("./routes/feedback");
app.use("/api/feedback", feedbackRoutes);
const moderationRoutes = require("./routes/moderation");
app.use("/api/moderation", moderationRoutes);
const eventRoutes = require("./routes/events");
app.use("/api/events", eventRoutes);
const notificationsRoutes = require("./routes/notifications");
app.use("/api/notifications", notificationsRoutes);
const analyticsRoutes = require("./routes/analytics");
app.use("/api/analytics", analyticsRoutes);
const securityRoutes = require("./routes/security");
app.use("/api/security", securityRoutes);
const feedbackRoutes = require("./routes/feedback");
app.use("/api/feedback", feedbackRoutes);
const pollsRoutes = require("./routes/polls");
app.use("/api/polls", pollsRoutes);
const i18nRoutes = require("./routes/i18n");
app.use("/api/i18n", i18nRoutes);
const i18nRoutes = require("./routes/i18n");
app.use("/api/i18n", i18nRoutes);
